New structure for model files (clean up) and new power law function
threeML/astromodels pull request #147
Opened 2021-03-18 08:06 UTC by grburgess

I have started cleaning up the functions file as it is getting crowded. I moved power law functions
to their own file as well as added a new power law normalized to its energy flux.

There are additionally some improved import statements to keep from polluting the environment.

2021-03-23 21:54 UTC, henrikef requested changes
See individual comments (just one small issue, really).

I'm getting tons of `NameError: name 'np' is not defined` in threeML with this version of astromodels. I assume this is related to changes in importing numpy. I'll try and see if I can add `import numpy as np` to threeML where needed. We should wait for that to be ready though before merging this.

2021-03-23 21:54 UTC, henrikef commented on astromodels/functions/dark_matter/dm_models.py
> +            print(
Change print to logging?

2021-03-24 13:22 UTC, grburgess commented
> See individual comments (just one small issue, really).
> 
> I'm getting tons of `NameError: name 'np' is not defined` in threeML with this version of astromodels. I assume this is related to changes in importing numpy. Fixed in [threeML/threeML#448](https://github.com/threeML/threeML/pull/448)

Ja, I cleaned this up because we were just importing everything from the modules with the import * stuff... in principle it is fine, but it might tick off someone wanting to use certain parts of 3ML etc. Also that was some baking coding on our part because we should've been importing those modules directly :)

2021-03-24 13:23 UTC, grburgess commented on astromodels/functions/dark_matter/dm_models.py
> +            print(
could do!

2021-03-24 13:28 UTC, grburgess commented on astromodels/functions/__init__.py
> +if has_naima:
woops. yup. fixed

2021-03-24 16:57 UTC, henrikef approved these changes
Looks good now, although I recommend waiting for https://github.com/threeML/threeML/pull/448 (CI keeps crashing during the tests due to low disk space, but everything worked locally)

2021-03-24 17:31 UTC, grburgess commented
@henrikef thanks! We can discuss in a few moments.

2021-04-01 18:28 UTC, merged